OP(NO_OP, "", "")
OP(OP_ADD, "+", "+")
OP(OP_SUB, "-", "-")
OP(OP_MUL, "*", "*")
OP(OP_DIV, "/", "/")
OP(FUN_SIN, "sin", "sin")
OP(FUN_COS, "cos", "cos")
OP(FUN_POW, "^", "^")
OP(FUN_SQRT, "sqrt", "sqrt")
OP(FUN_LN, "ln", "ln")
OP(DEFINE, "handing over to you", "")
OP(RET, "out", "return")
OP(OP_ASSIGN, "encoding matches", "= ") // exectly "= " (with space) so there is no space matches
OP(OP_LOOP, "reseption while", "while")
OP(OP_CONDITION, "reseption if", "if")
OP(INPUT, "give a signal", "input")
OP(OUTPUT, "get the message", "output")
OP(OP_ABOVE, "overflow", ">")
OP(OP_BELOW, "lacking", "<")
OP(OP_EQUAL, "match", "==")
OP(OP_NO_EQUAL, "diverse", "!=")
OP(OP_UN_SUB, "", "-")
OP(L_CURLY_BRACKET, "{", "{")
OP(R_CURLY_BRACKET, "}", "}")
OP(L_BRACKET, "(", "(")
OP(R_BRACKET, ")", ")")
OP(COMMA, ",", ",")
OP(SEMICOLON, ";", ";")
OP(END, "", "")